---
- name: Create autoload directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install minpac
  git:
    repo: git@github.com:k-takata/minpac.git
    dest: ~/.vim/pack/minpac/opt/minpac

- name: Create symlink for .vimrc
  file:
    src: "{{playbook_dir}}/files/dotfiles/.vimrc"
    dest: ~/.vimrc
    state: link
