---
- name: Update homebrew
  command: "brew update"

- name: Install base homebrew packages
  command: "brew install {{item.install_options | default('') }} {{ item.name }}"
  with_items: "{{ base_brew_packages }}"

- name: Install brew cask applications
  command: "brew cask install {{item.install_options | default('') }} {{ item.name }}"
  with_items: "{{ base_brew_cask_apps }}"